#!/usr/bin/env bash

# bash "strict mode"
set -eu

# check if macOS is running

    if test "$(uname)" != "Darwin"; then
        message fail "OS must be macOS"
        exit 0
    fi


# Install apps

    message info "Installing apps, fonts & quicklook plugins…"

    apps=(
        sourcetree
        sequel-pro
        virtualbox
        google-chrome
        firefox
        transmit
        bettertouchtool
        spotify
        vlc
        transmission
        macdown
        dropbox
    )

    brew cask install "${apps[@]}" --appdir=/Applications


# Install QuickLook plugins (https://github.com/sindresorhus/quick-look-plugins)

    ql=(
        qlcolorcode
        qlstephen
        qlmarkdown
        quicklook-json
        qlprettypatch
        quicklook-csv
        qlimagesize
        webpquicklook
        quicklookase
        qlvideo
        quicklook-pat
    )

    brew cask install "${ql[@]}"


# Install utilities

    utilities=(
        youtube-dl
        gifski
    )

    brew install ${utilities[@]}


# Install fonts

    fonts=(
      font-source-code-pro
      font-ibm-plex
    )
    brew cask install ${fonts[@]}


# Sublime

    brew cask install sublime-text --appdir=/Applications

    sublime-update-prefs
