#!/usr/bin/env bash


# Install homebrew

    if ! [ -x "$(command -v brew)" ]; then
        # Homebrew is missing, install it
        echo "Installing Homebrew…"
        ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
        brew update
        brew upgrade
    else
        echo "Homebrew is already installed, skipping…"
    fi;



# Install utilities

    echo "Installing brew utilities…"

    brew install coreutils
    brew install yarn --without-node

    brew tap caskroom/cask
    brew tap caskroom/fonts


# Install apps

    echo "Installing apps…"

    apps=(
        sourcetree
        sequel-pro
        virtualbox
        google-chrome
        firefox
        transmit
        bettertouchtool
        dropbox
        spotify
        vlc
        transmission
        macdown
    )

    brew cask install "${apps[@]}" --appdir=/Applications


# Install QuickLook plugins (https://github.com/sindresorhus/quick-look-plugins)

    echo "Installing quicklook plugins…"

    ql=(
        qlcolorcode
        qlstephen
        qlmarkdown
        quicklook-json
        qlprettypatch
        quicklook-csv
        qlimagesize
        webpquicklook
        quicklookase
        qlvideo
        quicklook-pat
    )

    brew cask install "${ql[@]}"


# Install fonts

    echo "Installing fonts…"

    fonts=(
      font-source-code-pro
      font-fira-code
    )
    brew cask install ${fonts[@]}


# Sublime

    echo "Installing sublime text…"

    brew cask install sublime-text --appdir=/Applications

    # move prefs into place
    mkdir -p ~/Library/Application\ Support/Sublime\ Text\ 3
    cp -af $DOTFILES/brew/sublime/Library/. ~/Library/Application\ Support/Sublime\ Text\ 3

    # replace icon
    rm -f /Applications/Sublime\ Text.app/Contents/Resources/Sublime\ Text.icns
    cp -f $DOTFILES/brew/sublime/Sublime\ Text.icns /Applications/Sublime\ Text.app/Contents/Resources/Sublime\ Text.icns
