#!/usr/bin/env bash

# check if macOS is running

    if test "$(uname)" != "Darwin"; then
        message fail "OS must be macOS"
        exit 0
    fi

# Install homebrew

    if ! [ -x "$(command -v brew)" ]; then
        # Homebrew is missing, install it
        message info "Installing brew"
        ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    else
        message info "brew is already installed, skipping…"
    fi;

    message info "brew updating…"

    brew update --quiet
    brew upgrade --quiet



# Install utilities

    message info "Installing brew utilities…"

    brew install coreutils --quiet
    brew install yarn --without-node --quiet

    brew tap caskroom/cask --quiet
    brew tap caskroom/fonts --quiet


# Install apps

    message info "Installing apps, fonts & quicklook plugins…"

    apps=(
        sourcetree
        sequel-pro
        virtualbox
        google-chrome
        firefox
        transmit
        bettertouchtool
        spotify
        vlc
        transmission
        macdown
    )

    brew cask install "${apps[@]}" --appdir=/Applications


# Install QuickLook plugins (https://github.com/sindresorhus/quick-look-plugins)

    ql=(
        qlcolorcode
        qlstephen
        qlmarkdown
        quicklook-json
        qlprettypatch
        quicklook-csv
        qlimagesize
        webpquicklook
        quicklookase
        qlvideo
        quicklook-pat
    )

    brew cask install "${ql[@]}"


# Install fonts

    fonts=(
      font-source-code-pro
      font-fira-code
    )
    brew cask install ${fonts[@]}


# Sublime

    brew cask install sublime-text --appdir=/Applications

    # move prefs into place
    mkdir -p ~/Library/Application\ Support/Sublime\ Text\ 3
    cp -af $DOTFILES/brew/sublime/Library/. ~/Library/Application\ Support/Sublime\ Text\ 3

    # replace icon
    rm -f /Applications/Sublime\ Text.app/Contents/Resources/Sublime\ Text.icns
    cp -f $DOTFILES/brew/sublime/Sublime\ Text.icns /Applications/Sublime\ Text.app/Contents/Resources/Sublime\ Text.icns


# done

    message success "${BASH_SOURCE[0]} completed"
