#!/usr/bin/env bash

# bash "strict mode"
set -eu

# check if macOS is running

    if test "$(uname)" != "Darwin"; then
        message fail "OS must be macOS"
        exit 0
    fi

# Install homebrew

    if ! [ -x $(command -v brew) ]; then
        message info "Installing brew"
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    else
        message info "brew is already installed, skipping…"
        HOMEBREW_PREFIX=$(brew --prefix)
    fi;

    message info "brew updating…"
    $HOMEBREW_PREFIX/bin/brew update --quiet
    $HOMEBREW_PREFIX/bin/brew upgrade --quiet
    brew analytics off


# Install brew utilities

    message info "Installing brew utilities…"
    $HOMEBREW_PREFIX/bin/brew install coreutils --quiet
    $HOMEBREW_PREFIX/bin/brew tap homebrew/cask --quiet
    $HOMEBREW_PREFIX/bin/brew tap homebrew/cask-fonts --quiet


# shell env path

    eval "$($HOMEBREW_PREFIX/bin/brew shellenv)"
