#!/usr/bin/env bash

set -eu
source ./deps


# Install brew

    HOMEBREW_PREFIX=$(getHomebrewPrefix)
    if [ -d "$HOMEBREW_PREFIX" ]; then
        message info "brew is already installed, skipping…"
    else
        message info "Installing brew"
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        HOMEBREW_PREFIX=$(getHomebrewPrefix)
        PATH=$PATH:$HOMEBREW_PREFIX/bin
    fi;    
    

# update and turn off analytics

    message info "brew updating…"
    brew update --quiet
    brew upgrade --quiet
    message info "brew disable analytics…"
    brew analytics off


# Install brew utilities

    message info "installing brew utilities…"
    brew install coreutils --quiet