#!/usr/bin/env bash

# enable colour output

export CLICOLOR=1
export LSCOLORS=ExFxBxDxCxegedabagacad


# Case-insensitive globbing (used in pathname expansion)
# and exclude, e.g. ls !(folder)

if [ -n "$ZSH_VERSION" ]; then
	setopt extendedglob
	unsetopt CASE_GLOB
elif [ -n "$BASH_VERSION" ]; then
	shopt -s extglob
	shopt -s nocaseglob
fi


# Autocorrect typos in path names when using `cd`

if [ -n "$BASH_VERSION" ]; then
	shopt -s cdspell
fi


# Highlight section titles in man pages

export LESS_TERMCAP_mb=$(printf '\e[01;31m') # enter blinking mode – red
export LESS_TERMCAP_md=$(printf '\e[01;35m') # enter double-bright mode – bold, magenta
export LESS_TERMCAP_me=$(printf '\e[0m') # turn off all appearance modes (mb, md, so, us)
export LESS_TERMCAP_se=$(printf '\e[0m') # leave standout mode
export LESS_TERMCAP_so=$(printf '\e[01;33m') # enter standout mode – yellow
export LESS_TERMCAP_ue=$(printf '\e[0m') # leave underline mode
export LESS_TERMCAP_us=$(printf '\e[04;36m') # enter underline mode – cyan


# Do not autocomplete when accidentally pressing Tab on an empty line.

if [ -n "$BASH_VERSION" ]; then
	shopt -s no_empty_cmd_completion
fi

