#!/usr/bin/env bash

if [[ -n "$BASH_VERSION" ]]; then
   esc1="\["
   esc2="\]"
   workingDir="\w"
   # alternative symbols: ◆ * ☞ ❯ → λ
   symbol="λ" 
elif [[ -n "$ZSH_VERSION" ]]; then
   setopt PROMPT_SUBST
   esc1="%{"
   esc2="%}"
   workingDir="%~"
   symbol="❯"
fi

# set colours


reset="${esc1}$(tput sgr0)${esc2}"
bold="${esc1}$(tput bold)${esc2}"
black="${esc1}$(tput setaf 0)${esc2}"
blue="${esc1}$(tput setaf 33)${esc2}"
cyan="${esc1}$(tput setaf 37)${esc2}"
green="${esc1}$(tput setaf 64)${esc2}"
orange="${esc1}$(tput setaf 166)${esc2}"
magenta="${esc1}$(tput setaf 125)${esc2}"
red="${esc1}$(tput setaf 124)${esc2}"
violet="${esc1}$(tput setaf 61)${esc2}"
white="${esc1}$(tput setaf 15)${esc2}"
yellow="${esc1}$(tput setaf 136)${esc2}"
purpleDark="$(tput setaf 18)"
lilac="$(tput setaf 60)"
dim="$(tput setaf 238)"
bgBlack="${esc1}$(tput setab 8)${esc2}"
bgBlackLight="${esc1}$(tput setab 0)${esc2}"

# Set prompt

newline=$'\n'
PS1="${reset}"
PS1+="${bgBlackLight}${violet}\$(git_prompt)${reset}"
PS1+="${bgBlack}${magenta}${bold} ${workingDir} ${reset} ${white}${symbol} " 
PS1="${newline}$PS1"

PS2="${magenta}→ ${reset}"


if [[ -n "$BASH_VERSION" ]]; then
	export PS1
   export PS2
elif [[ -n "$ZSH_VERSION" ]]; then
   PROMPT="$PS1"
   PROMPT2="$PS2"
fi