#!/usr/bin/env bash

# variables

    DOTFILES=~/.dotfiles  

# Ask for the administrator password upfront

    echo "Installing dotfiles at $HOME/.dotfiles"

    mkdir -p $DOTFILES && cd $DOTFILES 

    touch ~/.bash_profile

    if ! grep -Fq "source ~/.dotfiles/env" ~/.bash_profile ; then
        echo -e "# edit dotfiles in ~/.dotfiles \nsource ~/.dotfiles/env" >> ~/.bash_profile
        source ~/.bash_profile
    fi

    touch ~/.bashrc

    if ! grep -Fq "source ~/.bash_profile" ~/.bash_profile ; then
        echo -e "# edit dotfiles in ~/.dotfiles \nsource ~/.bash_profile" >> ~/.bashrc
    fi

