#!/usr/bin/env bash

# dotfiles location 

    export DOTFILES="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

    echo "Installing dotfiles at $DOTFILES"

    mkdir -p $DOTFILES && cd $DOTFILES 

# source shell env inside .bash_profile and .bashrc

    touch ~/.bash_profile && touch ~/.bashrc
 
    if ! grep -Fq "source ~/.bashrc" ~/.bash_profile ; then
        echo -e "# edit dotfiles in $DOTFILES \nsource ~/.bashrc" >> ~/.bash_profile
    fi    

    if ! grep -Fq "source $DOTFILES/env" ~/.bashrc ; then
        echo -e "# edit dotfiles in $DOTFILES \nsource $DOTFILES/env" >> ~/.bashrc
    fi

# source shell env, and run help command

    source $DOTFILES/env

    dotfiles files
    dotfiles help

    source ~/.bash_profile