#!/usr/bin/env bash

if ! [ -d ~/.nvm ]; then

	PWD = $(pwd);

    export NVM_DIR="$HOME/.nvm" && (
        git clone https://github.com/creationix/nvm.git "$NVM_DIR"
        cd "$NVM_DIR"
        git checkout `git describe --abbrev=0 --tags --match "v[0-9]*" origin`
    ) && . "$NVM_DIR/nvm.sh"

    cd $PWD;

    # and install node
    nvm install node

else
    echo "nvm already installed, skipping…"
fi;