#!/usr/bin/env bash

if ! [ -d ~/.nvm ]; then

    message info "Installing nvm…"

    export NVM_DIR="$HOME/.nvm" && (
        git clone https://github.com/creationix/nvm.git "$NVM_DIR" --quiet
        cd "$NVM_DIR"
        git checkout `git describe --abbrev=0 --tags --match "v[0-9]*" origin` --quiet
    ) && . "$NVM_DIR/nvm.sh"

    nvm install node

    message success "Installed nvm"

else
    message info "nvm already installed, skipping…"
fi;


# done

    message success "${BASH_SOURCE[0]} completed"