#!/usr/bin/env bash

set -eu

if ! [ -d ~/.nvm ]; then
    message info "Installing nvm…"
    export NVM_DIR="$HOME/.nvm"
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash
    source "$NVM_DIR/nvm.sh"
    nvm install node
    message success "Installed nvm"

else
    message info "nvm already installed, skipping…"
fi;
