#!/usr/bin/env bash

# bash "strict mode"
set -eu

# stop/remove previous apache builds

    (
        # built-in apache
        sudo apachectl stop
        sudo launchctl unload -w /System/Library/LaunchDaemons/org.apache.httpd.plist 2>/dev/null
        # brew-installed apache
        sudo brew services stop httpd
        brew uninstall httpd
        sudo rm -rf /usr/local/etc/httpd

    ) > /dev/null 2>&1 || message info "Apache errored while removing old version"

# install

    brew install httpd lynx

    # start on :8080
    sudo brew services start httpd

# configure

    apacheconf=/usr/local/etc/httpd/httpd.conf
    sslconf=/usr/local/etc/httpd/extra/httpd-ssl.conf

    # listen on port 80
    sed -i '' 's/^Listen 8080/Listen 80/' $apacheconf

    # move document root
    sed -i '' "s|^DocumentRoot \"/usr/local/var/www\"|DocumentRoot \"$HOME/Projects/localhost\"|g" $apacheconf
    sed -i '' "s|^<Directory \"/usr/local/var/www\">|<Directory \"$HOME/Projects\">|g" $apacheconf

    # set ServerName
    sed -i '' 's/^#ServerName.*/ServerName localhost/g' $apacheconf

    # allow .htaccess
    sed -i '' 's/AllowOverride.*None/AllowOverride All/g' $apacheconf

    # change user and group
    sed -i '' "s/^User.*/User $(whoami)/" $apacheconf
    sed -i '' "s/^Group.*/Group staff/" $apacheconf

    # enable httpd-vhosts.conf
    sed -i '' 's|^ *#Include\(.*\/\)httpd-vhosts.conf|Include\1httpd-vhosts.conf|g' $apacheconf

    #enable mod_rewrite
    sed -i '' 's|^ *#LoadModule *rewrite_module|LoadModule rewrite_module|g' $apacheconf

    #enable mod_vhost_alias
    sed -i '' 's|^ *#LoadModule *vhost_alias_module|LoadModule vhost_alias_module|g' $apacheconf

    #enable mod_http2
    sed -i '' 's|^ *#LoadModule *http2_module|LoadModule http2_module|g' $apacheconf

    #enable ssl
    sed -i '' 's|^ *#LoadModule *ssl_module|LoadModule ssl_module|g' $apacheconf
    sed -i '' 's|^ *#LoadModule *socache_shmcb_module|LoadModule socache_shmcb_module|g' $apacheconf
    sed -i '' 's|^ *#Include\(.*\/\)httpd-ssl.conf|Include\1httpd-ssl.conf|g' $apacheconf

    sed -i '' 's|^Listen 8443|Listen 443|g' $sslconf
    sed -i '' 's|<VirtualHost _default_:8443>|<VirtualHost _default_:443>|g' $sslconf
    sed -i '' "s|^DocumentRoot \"/usr/local/var/www\"|DocumentRoot \"$HOME/Projects/localhost\"|g" $sslconf
    sed -i '' 's|^ServerName.*|ServerName localhost:443|g' $sslconf

    mkdir -p $HOME/Projects/localhost

    cd /usr/local/etc/httpd

    openssl req \
    -new \
    -newkey rsa:4096 \
    -days 365 \
    -nodes \
    -x509 \
    -subj "/C=GB/ST=localhost/L=localhost/O=localhost/CN=localhost" \
    -keyout server.key \
    -out server.crt
    

# restart apache
sudo apachectl -k restart