#!/usr/bin/env bash

# bash "strict mode"
set -eu

# install 5.7
brew install mysql@5.7
brew link mysql@5.7 --force

# if there are any issues, try to load/unload using brew services start/stop mysql

# opens mysql_secure_installation in a new terminal window
osascript -e 'tell application "Terminal" to do script "mysql_secure_installation"'
