#!/usr/bin/env bash

# install mysql 8.0
set -eu
brew install mysql@8.0
brew link mysql@8.0 --force
brew services start mysql

# opens mysql_secure_installation in a new terminal window
osascript -e 'tell application "Terminal" to do script "mysql_secure_installation"'

# Known problem: 
# "MySQL said: Authentication plugin 'caching_sha2_password' cannot be loaded"
#	mysql -u root -p
#	> ALTER USER root@localhost IDENTIFIED WITH mysql_native_password BY 'YOUR_PASSWORD';