#!/usr/bin/env bash
    
# remove old Apache versions, and install fresh

    HOMEBREW_PATH=$(brew --prefix)
    DIR="$( cd "$( dirname "${BASH_SOURCE[0]:-${(%):-%x}}" )" && pwd )"

    # remove brew-installed apache
    echo "Stop existing httpd services"
    brew services stop httpd &> /dev/null
    sudo brew services stop httpd &> /dev/null
    brew remove httpd --force &> /dev/null
    brew unlink httpd &> /dev/null
    
    echo "Delete old installations…"
    sudo rm -rf "$(brew --cellar httpd)" &> /dev/null

    # stop built-in apache from running
    echo 'Stop built-in apache'
    sudo /usr/sbin/apachectl stop &> /dev/null
    sudo launchctl unload -w /System/Library/LaunchDaemons/org.apache.httpd.plist &> /dev/null


# set bail early (after stop commands), and install

    set -eu
    brew install httpd
    brew services start httpd

# configure
    
    apacheconf="$HOMEBREW_PATH/etc/httpd/httpd.conf"
    vhostconf="$HOMEBREW_PATH/etc/httpd/extra/httpd-vhosts.conf"
    sslconf="$HOMEBREW_PATH/etc/httpd/extra/httpd-ssl.conf"

    # listen on port 80
    # sed -i '' 's/^Listen 8080/Listen 8080/' $apacheconf

    # move document root
    sed -i '' "s|^DocumentRoot \"$HOMEBREW_PATH/var/www\"|DocumentRoot \"$HOME/Projects/localhost\"|g" $apacheconf
    sed -i '' "s|^<Directory \"$HOMEBREW_PATH/var/www\">|<Directory \"$HOME/Projects\">|g" $apacheconf

    # set ServerName
    sed -i '' 's/^#ServerName.*/ServerName localhost/g' $apacheconf

    # allow .htaccess
    sed -i '' 's/AllowOverride.*None/AllowOverride All/g' $apacheconf

    # change user and group
    sed -i '' "s/^User.*/User $(whoami)/" $apacheconf
    sed -i '' "s/^Group.*/Group staff/" $apacheconf

    # enable httpd-vhosts.conf
    sed -i '' 's|^ *#Include\(.*\/\)httpd-vhosts.conf|Include\1httpd-vhosts.conf|g' $apacheconf

    #enable mod_rewrite
    sed -i '' 's|^ *#LoadModule *rewrite_module|LoadModule rewrite_module|g' $apacheconf

    #enable mod_vhost_alias
    sed -i '' 's|^ *#LoadModule *vhost_alias_module|LoadModule vhost_alias_module|g' $apacheconf

    #enable mod_http2
    sed -i '' 's|^ *#LoadModule *http2_module|LoadModule http2_module|g' $apacheconf

    #enable ssl
    sed -i '' 's|^ *#LoadModule *ssl_module|LoadModule ssl_module|g' $apacheconf
    sed -i '' 's|^ *#LoadModule *socache_shmcb_module|LoadModule socache_shmcb_module|g' $apacheconf
    sed -i '' 's|^ *#Include\(.*\/\)httpd-ssl.conf|Include\1httpd-ssl.conf|g' $apacheconf

    # sed -i '' 's|^Listen 8443|Listen 443|g' $sslconf
    # sed -i '' 's|<VirtualHost _default_:8443>|<VirtualHost _default_:443>|g' $sslconf
    sed -i '' "s|^DocumentRoot \"$HOMEBREW_PATH/var/www\"|DocumentRoot \"$HOME/Projects/localhost\"|g" $sslconf
    # sed -i '' 's|^ServerName.*|ServerName localhost:443|g' $sslconf

    mkdir -p $HOME/Projects/localhost

    cd $HOMEBREW_PATH/etc/httpd

    openssl req \
    -new \
    -newkey rsa:4096 \
    -days 365 \
    -nodes \
    -x509 \
    -subj "/C=GB/ST=localhost/L=localhost/O=localhost/CN=localhost" \
    -keyout server.key \
    -out server.crt

    # replace standard file with vhost template

    if grep -qF 'dummy-host.example.com' $vhostconf; then
        mv $vhostconf "$vhostconf.original"
        cp "$DIR/httpd-vhosts.conf" $vhostconf;
        sed -i '' "s|{projects}|$HOME/Projects|g" $vhostconf
        sed -i '' "s|{sslCert}|$HOMEBREW_PATH/etc/httpd/server.crt|g" $vhostconf
        sed -i '' "s|{sslKey}|$HOMEBREW_PATH/etc/httpd/server.key|g" $vhostconf
    fi

    open $vhostconf
    

# restart apache
echo 'Restarting apache'
sudo apachectl -k restart