#!/usr/bin/env bash

# bash "strict mode"
set -eu

# install

	brew tap homebrew/php

	brew install php72 --with-httpd

	brew install php72-opcache php72-apcu php72-xdebug php72-yaml --build-from-source

# configure

	apacheconf=/usr/local/etc/httpd/httpd.conf
	phpini=/usr/local/etc/php/7.2/php.ini

	#apache changes
	sed -i '' 's|LoadModule php7_module.*|LoadModule php7_module /usr/local/opt/php72/libexec/apache2/libphp7.so|g' $apacheconf

	#php directory index
    sed -i '' 's|DirectoryIndex.*|DirectoryIndex index.php index.html|g' $apacheconf

    # add php handler if no matches
    if ! grep 'SetHandler.*application/x-httpd-php' $apacheconf ; then
	    echo '<FilesMatch \.php$>
		    SetHandler application/x-httpd-php
		</FilesMatch>' >> $apacheconf
    fi;

# restart apache

sudo apachectl -k restart