#!/usr/bin/env bash


# vars

	HOMEBREW_PATH=$(brew --prefix)
	apacheconf="$HOMEBREW_PATH/etc/httpd/httpd.conf"


# install
	# set -eu
	# brew install curl php autoconf
	# xdebug=$( pecl install xdebug ) || message fail "xdebug" && echo "$xdebug"


# configure

	phpmod="$HOMEBREW_PATH/opt/php/lib/httpd/modules/libphp.so"

	# edit httpd.conf to load php module
	sed -i '' "s|LoadModule php_module.*|LoadModule php_module $phpmod|g" $apacheconf
	if ! grep 'LoadModule php_module.*' $apacheconf > /dev/null ; then
		printf "LoadModule php_module $phpmod \n" >> $apacheconf
	fi;

	# php directory index
    sed -i '' 's|DirectoryIndex\(.*\)index.html|DirectoryIndex index.php\1index.html|g' $apacheconf

    # add php handler if no matches
    if ! grep 'SetHandler.*application/x-httpd-php' $apacheconf > /dev/null ; then
	    echo "<FilesMatch .php$>
	    	SetHandler application/x-httpd-php
	    </FilesMatch>" >> $apacheconf
    fi;


# restart apache

sleep 1; sudo apachectl graceful
